name: Test and Publish JSR Module

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  test:
    uses: CodrJS/cicd/.github/workflows/deno-test.yml@main
  publish:
    uses: CodrJS/cicd/.github/workflows/deno-publish-jsr.yml@main
    needs: test
    secrets: inherit
